CREATE SCHEMA `heyparking` DEFAULT CHARACTER SET utf8mb4 ;

CREATE TABLE `heyparking`.`TB_PARKING_INFO` (
    `PK_PARKING` INT NOT NULL AUTO_INCREMENT COMMENT '주차장 정보 PK',
    `UQ_PARKING` VARCHAR(45) NOT NULL COMMENT '주차장 정보 UNIQUE KEY',
    `PARKING_NAME` VARCHAR(100) NOT NULL COMMENT '주차장 명',
    `PARKING_ADDR` VARCHAR(500) NOT NULL COMMENT '주차장 주소',
    `PARKING_TOTAL_NUM` VARCHAR(100) NOT NULL COMMENT '주차면수',
    `PARKING_EMPTY_NUM` VARCHAR(100) NOT NULL DEFAULT -1 COMMENT '주차장 빈자리 수',
    `PARKING_LAT` VARCHAR(200) NOT NULL DEFAULT 0 COMMENT '위도',
    `PARKING_LON` VARCHAR(200) NOT NULL DEFAULT 0 COMMENT '경도',
    `UPDATE_DATE` DATE NOT NULL COMMENT '업데이트 날짜',
    `UPDATE_TIME` TIME NOT NULL COMMENT '업데이트 시간',
    PRIMARY KEY (`PK_PARKING`),
    UNIQUE INDEX `UQ_PARKING_UNIQUE` (`UQ_PARKING` ASC) VISIBLE)
    ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '주자창 정보';

